services:

  unbound-mailcow:
    image: ghcr.io/mailcow/unbound:1.24
    environment:
      - TZ=${TZ}
      - SKIP_UNBOUND_HEALTHCHECK=${SKIP_UNBOUND_HEALTHCHECK:-n}
    volumes:
      - ./data/hooks/unbound:/hooks:Z
      - ./data/conf/unbound/unbound.conf:/etc/unbound/unbound.conf:ro,Z
    restart: always
    tty: true
    networks:
      mailcow-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.254
        aliases:
          - unbound

  mysql-mailcow:
    image: mariadb:10.11
    depends_on:
      - unbound-mailcow
      - netfilter-mailcow
    stop_grace_period: 45s
    volumes:
      - mysql-vol-1:/var/lib/mysql/
      - mysql-socket-vol-1:/var/run/mysqld/:z
      - ./data/conf/mysql/:/etc/mysql/conf.d/:ro,Z
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${DBROOT}
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_INITDB_SKIP_TZINFO=1
    restart: always
    ports:
      - "${SQL_PORT:-127.0.0.1:13306}:3306"
    networks:
      mailcow-network:
        aliases:
          - mysql

  redis-mailcow:
    image: redis:7.4.6-alpine
    entrypoint: ["/bin/sh","/redis-conf.sh"]
    volumes:
      - redis-vol-1:/data/
      - ./data/conf/redis/redis-conf.sh:/redis-conf.sh:z
    restart: always
    depends_on:
      - netfilter-mailcow
    ports:
      - "${REDIS_PORT:-127.0.0.1:7654}:6379"
    environment:
      - TZ=${TZ}
      - REDISPASS=${REDISPASS}
      - REDISMASTERPASS=${REDISMASTERPASS:-}
    sysctls:
      - net.core.somaxconn=4096
    networks:
      mailcow-network:
        ipv4_address: ${IPV4_NETWORK:-172.22.1}.249
        aliases:
          - redis

  clamd-mailcow:
    image: ghcr.io/mailcow/clamd:1.71
    restart: always
    depends_on:
      unbound-mailcow:
        condition: service_healthy
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    environment:
      - TZ=${TZ}
      - SKIP_CLAMD=${SKIP_CLAMD:-n}
    volumes:
      - ./data/conf/clamav/:/etc/clamav/:Z
      - clamd-db-vol-1:/var/lib/clamav
    networks:
      mailcow-network:
        aliases:
          - clamd

  rspamd-mailcow:
    image: ghcr.io/mailcow/rspamd:2.4
    stop_grace_period: 30s
    depends_on:
      - dovecot-mailcow
      - clamd-mailcow
    environment:
      - TZ=${TZ}
      - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
      - REDISPASS=${REDISPASS}
      - SPAMHAUS_DQS_KEY=${SPAMHAUS_DQS_KEY:-}
    volumes:
      - ./data/hooks/rspamd:/hooks:Z
      - ./data/conf/rspamd/custom/:/etc/rspamd/custom:z
      - ./data/conf/rspamd/override.d/:/etc/rspamd/override.d:Z
      - ./data/conf/rspamd/local.d/:/etc/rspamd/local.d:Z
      - ./data/conf/rspamd/plugins.d/:/etc/rspamd/plugins.d:Z
      - ./data/conf/rspamd/lua/:/etc/rspamd/lua/:ro,Z
      - ./data/conf/rspamd/rspamd.conf.local:/etc/rspamd/rspamd.conf.local:Z
      - ./data/conf/rspamd/rspamd.conf.override:/etc/rspamd/rspamd.conf.override:Z
      - rspamd-vol-1:/var/lib/rspamd
    restart: always
    hostname: rspamd
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    networks:
      mailcow-network:
        aliases:
          - rspamd

  php-fpm-mailcow:
    image: ghcr.io/mailcow/phpfpm:1.94
    command: "php-fpm -d date.timezone=${TZ} -d expose_php=0"
    depends_on:
      - redis-mailcow
    volumes:
      # (all your volumes remain unchanged)
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    environment:
      # (all your env vars remain unchanged)
    restart: always
    networks:
      mailcow-network:
        aliases:
          - phpfpm

  sogo-mailcow:
    image: ghcr.io/mailcow/sogo:1.136
    environment:
      # (all your env vars remain unchanged)
    dns:
      - ${IPV4_NETWORK:-172.22.1}.254
    volumes:
      # (all your volumes remain unchanged)
    restart: always
    networks:
      mailcow-network:
        aliases:
          - sogo

# --------------------
# Volumes
volumes:
  mysql-vol-1:
  mysql-socket-vol-1:
  redis-vol-1:
  clamd-db-vol-1:
  rspamd-vol-1:

# --------------------
# Network
networks:
  mailcow-network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
        - subnet: fd4d:6169:6c63:6f77::/64
